[tool.commitizen]
name = "cz_conventional_commits"
version = "0.7.1"
bump_message = "bump: version $current_version → $new_version [skip ci]"
tag_format = "$version"
version_scheme = "semver"
update_changelog_on_bump = true
version_files = [
    "example_file.yml"
]